In [1]:
import math
import pandas as pd
import numpy as np
import os
# print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.
import itertools
import os

%matplotlib inline
import matplotlib.pyplot as plt

import tensorflow as tf

from sklearn.preprocessing import LabelBinarizer, LabelEncoder
from sklearn.metrics import confusion_matrix

from tensorflow import keras
layers = keras.layers
models = keras.models

In [2]:
data = pd.read_csv("sonar.csv", header=None)
data.head()
copy1 = data.copy()
print(data.shape)
len(data)


(208, 61)


208

In [3]:
dt = np.array(data)
shuffle_dt= np.random.shuffle(dt)
print(dt)
len(dt)


[[0.0179 0.0136 0.0408 ... 0.016 0.0085 'M']
 [0.0126 0.0519 0.0621 ... 0.0114 0.0077 'R']
 [0.043 0.0902 0.0833 ... 0.0059 0.0021 'M']
 ...
 [0.0264 0.0071 0.0342 ... 0.0078 0.0066 'M']
 [0.0217 0.0152 0.0346 ... 0.0022 0.0032 'M']
 [0.0093 0.0185 0.0056 ... 0.0058 0.0025 'R']]


208

In [4]:
train_size=math.floor(int(len(dt)*.7))
print(train_size)
test_size = math.floor(int(len(dt)*.2))
print(test_size)
validation_size = math.floor (int(len(dt)*.1))
print(validation_size)

145+41+20

145
41
20


206

In [5]:
print(shuffle_dt)
train_data= dt[:train_size, :60].astype('float')
print(train_data)
print(len(train_data))
print(train_data.dtype)
test_data=dt[train_size:185,:60].astype('float')
print(test_data)
print(len(test_data))
validation_data = dt[185:205,:60].astype('float')
print(validation_data)   
print(len(validation_data))


None
[[0.0179 0.0136 0.0408 ... 0.0155 0.016  0.0085]
 [0.0126 0.0519 0.0621 ... 0.0034 0.0114 0.0077]
 [0.043  0.0902 0.0833 ... 0.0162 0.0059 0.0021]
 ...
 [0.0473 0.0509 0.0819 ... 0.0082 0.0028 0.0027]
 [0.0195 0.0142 0.0181 ... 0.0042 0.0067 0.0012]
 [0.0208 0.0186 0.0131 ... 0.0019 0.0049 0.0023]]
145
float64
[[0.0039 0.0063 0.0152 ... 0.0003 0.0053 0.0036]
 [0.0394 0.042  0.0446 ... 0.0068 0.0053 0.0087]
 [0.0353 0.0713 0.0326 ... 0.0096 0.0093 0.0053]
 ...
 [0.0303 0.0353 0.049  ... 0.0079 0.0036 0.0048]
 [0.0126 0.0149 0.0641 ... 0.0094 0.0116 0.0063]
 [0.0162 0.0041 0.0239 ... 0.0036 0.0053 0.003 ]]
40
[[0.0137 0.0297 0.0116 ... 0.0035 0.0043 0.0033]
 [0.0336 0.0294 0.0476 ... 0.0015 0.0069 0.0051]
 [0.0201 0.0178 0.0274 ... 0.002  0.0048 0.0036]
 ...
 [0.0202 0.0104 0.0325 ... 0.0054 0.0073 0.0054]
 [0.0231 0.0351 0.003  ... 0.0038 0.0043 0.003 ]
 [0.0096 0.0404 0.0682 ... 0.0036 0.0043 0.0018]]
20


In [6]:
train_label = dt[:train_size, 60]
print(train_label)
print(len(train_label))
test_label=dt[train_size:185,60]
print(test_label)
print(len(test_label))
validation_label = dt[185:205,60]
print(validation_label)
print(len(validation_label))

['M' 'R' 'M' 'M' 'M' 'R' 'R' 'M' 'M' 'M' 'M' 'M' 'R' 'R' 'R' 'R' 'R' 'R'
 'M' 'R' 'M' 'M' 'R' 'M' 'M' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'M' 'M' 'M' 'R'
 'R' 'R' 'M' 'R' 'M' 'R' 'R' 'M' 'R' 'M' 'R' 'R' 'R' 'M' 'R' 'M' 'M' 'R'
 'R' 'M' 'R' 'M' 'R' 'M' 'R' 'M' 'M' 'M' 'R' 'R' 'R' 'M' 'R' 'M' 'R' 'R'
 'R' 'M' 'M' 'M' 'R' 'M' 'M' 'M' 'M' 'M' 'M' 'R' 'M' 'M' 'R' 'R' 'M' 'R'
 'R' 'M' 'R' 'R' 'R' 'M' 'M' 'M' 'M' 'R' 'M' 'M' 'M' 'M' 'R' 'R' 'M' 'M'
 'R' 'R' 'M' 'M' 'R' 'R' 'R' 'R' 'M' 'M' 'R' 'M' 'M' 'M' 'R' 'M' 'M' 'R'
 'R' 'M' 'M' 'M' 'R' 'R' 'M' 'M' 'M' 'M' 'R' 'M' 'M' 'M' 'R' 'R' 'R' 'R'
 'R']
145
['R' 'M' 'R' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'R' 'R' 'M' 'M' 'R' 'M' 'R' 'M'
 'R' 'M' 'M' 'M' 'R' 'M' 'M' 'M' 'R' 'R' 'R' 'M' 'M' 'R' 'M' 'R' 'M' 'R'
 'M' 'M' 'R' 'M']
40
['M' 'R' 'M' 'R' 'R' 'M' 'M' 'M' 'R' 'M' 'R' 'M' 'R' 'M' 'M' 'R' 'R' 'R'
 'R' 'M']
20


In [7]:


encoder = LabelEncoder()
encoder.fit(dt[:,60:61])

y_train = encoder.transform(train_label)
y_train_v = encoder.transform(validation_label)
y_test = encoder.transform(test_label)



C:\Users\alida\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [8]:
print(train_data)
print(y_train)

[[0.0179 0.0136 0.0408 ... 0.0155 0.016  0.0085]
 [0.0126 0.0519 0.0621 ... 0.0034 0.0114 0.0077]
 [0.043  0.0902 0.0833 ... 0.0162 0.0059 0.0021]
 ...
 [0.0473 0.0509 0.0819 ... 0.0082 0.0028 0.0027]
 [0.0195 0.0142 0.0181 ... 0.0042 0.0067 0.0012]
 [0.0208 0.0186 0.0131 ... 0.0019 0.0049 0.0023]]
[0 1 0 0 0 1 1 0 0 0 0 0 1 1 1 1 1 1 0 1 0 0 1 0 0 1 1 1 1 1 1 1 0 0 0 1 1
 1 0 1 0 1 1 0 1 0 1 1 1 0 1 0 0 1 1 0 1 0 1 0 1 0 0 0 1 1 1 0 1 0 1 1 1 0
 0 0 1 0 0 0 0 0 0 1 0 0 1 1 0 1 1 0 1 1 1 0 0 0 0 1 0 0 0 0 1 1 0 0 1 1 0
 0 1 1 1 1 0 0 1 0 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 1 0 0 0 1 1 1 1 1]


In [9]:
epoch = 80
model = models.Sequential()
model.add(layers.Dense(16, activation='relu', input_shape=(60,)))
model.add(layers.Dense(8, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))
model.compile(optimizer = 'rmsprop' ,loss='binary_crossentropy',metrics=['accuracy'])
history = model.fit(train_data,
    y_train,
    epochs=epoch,
    batch_size=512)


Train on 145 samples
Epoch 1/80
145/145 [==============================] - 2s 15ms/sample - loss: 0.7053 - accuracy: 0.5103
Epoch 2/80
145/145 [==============================] - 0s 45us/sample - loss: 0.6987 - accuracy: 0.5103
Epoch 3/80
145/145 [==============================] - 0s 31us/sample - loss: 0.6947 - accuracy: 0.5103
Epoch 4/80
145/145 [==============================] - 0s 61us/sample - loss: 0.6917 - accuracy: 0.5103
Epoch 5/80
145/145 [==============================] - 0s 34us/sample - loss: 0.6888 - accuracy: 0.5103
Epoch 6/80
145/145 [==============================] - 0s 88us/sample - loss: 0.6862 - accuracy: 0.5103
Epoch 7/80
145/145 [==============================] - 0s 54us/sample - loss: 0.6840 - accuracy: 0.5103
Epoch 8/80
145/145 [==============================] - 0s 34us/sample - loss: 0.6822 - accuracy: 0.5103
Epoch 9/80
145/145 [==============================] - 0s 42us/sample - loss: 0.6806 - accuracy: 0.5103
Epoch 10/80
145/145 [==============================]

Epoch 80/80
145/145 [==============================] - 0s 60us/sample - loss: 0.5841 - accuracy: 0.6897


In [10]:
history_dict = history.history
history_dict.keys()


dict_keys(['loss', 'accuracy'])

In [11]:
history_validation = model.fit(train_data,
    y_train,
    epochs=epoch,
    batch_size=8,
    validation_data=(validation_data, y_train_v))


Train on 145 samples, validate on 20 samples
Epoch 1/80
145/145 [==============================] - 0s 3ms/sample - loss: 0.5864 - accuracy: 0.6828 - val_loss: 0.6074 - val_accuracy: 0.7500
Epoch 2/80
145/145 [==============================] - 0s 767us/sample - loss: 0.5810 - accuracy: 0.7586 - val_loss: 0.5983 - val_accuracy: 0.6500
Epoch 3/80
145/145 [==============================] - 0s 542us/sample - loss: 0.5733 - accuracy: 0.7379 - val_loss: 0.5968 - val_accuracy: 0.6500
Epoch 4/80
145/145 [==============================] - 0s 519us/sample - loss: 0.5640 - accuracy: 0.7448 - val_loss: 0.6121 - val_accuracy: 0.6000
Epoch 5/80
145/145 [==============================] - 0s 544us/sample - loss: 0.5598 - accuracy: 0.7034 - val_loss: 0.5882 - val_accuracy: 0.7000
Epoch 6/80
145/145 [==============================] - 0s 740us/sample - loss: 0.5504 - accuracy: 0.7310 - val_loss: 0.5847 - val_accuracy: 0.8000
Epoch 7/80
145/145 [==============================] - 0s 615us/sample - loss: 0.5

145/145 [==============================] - 0s 580us/sample - loss: 0.2774 - accuracy: 0.9103 - val_loss: 0.5412 - val_accuracy: 0.7500
Epoch 57/80
145/145 [==============================] - 0s 617us/sample - loss: 0.2719 - accuracy: 0.9034 - val_loss: 0.5284 - val_accuracy: 0.7500
Epoch 58/80
145/145 [==============================] - 0s 622us/sample - loss: 0.2649 - accuracy: 0.9103 - val_loss: 0.5380 - val_accuracy: 0.7500
Epoch 59/80
145/145 [==============================] - 0s 657us/sample - loss: 0.2600 - accuracy: 0.9103 - val_loss: 0.5383 - val_accuracy: 0.7000
Epoch 60/80
145/145 [==============================] - 0s 607us/sample - loss: 0.2684 - accuracy: 0.8897 - val_loss: 0.5652 - val_accuracy: 0.7500
Epoch 61/80
145/145 [==============================] - 0s 655us/sample - loss: 0.2612 - accuracy: 0.9172 - val_loss: 0.5465 - val_accuracy: 0.7500
Epoch 62/80
145/145 [==============================] - 0s 625us/sample - loss: 0.2589 - accuracy: 0.9103 - val_loss: 0.5530 - val_